/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.time.LocalDate;

/**
 *
 * @author dhiyas
 */
public class CreditCardPayingScreenUI extends javax.swing.JFrame {

    /**
     * Creates new form CreditCardPayingScreen
     */
    public CreditCardPayingScreenUI() {

        initComponents();
        emailLab.setVisible(false);
        emailTF.setVisible(false);
        LocalDate currentDate = LocalDate.now();
        yearSlider.setMaximum(currentDate.getYear() + 5);
        yearSlider.setMinimum(currentDate.getYear());
        monthSlider.setValue(1);
        monthLab.setText("1");
        yearLab.setText(currentDate.getYear() + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FinishPaymentBut = new javax.swing.JButton();
        sendReceiptRB = new javax.swing.JRadioButton();
        cardNumberTF = new javax.swing.JTextField();
        cardHolderNameTF = new javax.swing.JTextField();
        CVVTF = new javax.swing.JTextField();
        cardHolderNameLab = new javax.swing.JLabel();
        emailLab = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        cardNumberLab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        CVVLab = new javax.swing.JLabel();
        amountLab = new javax.swing.JLabel();
        yearLab = new javax.swing.JLabel();
        yearSlider = new javax.swing.JSlider();
        monthSlider = new javax.swing.JSlider();
        monthLab = new javax.swing.JLabel();
        emailErrorLab = new javax.swing.JLabel();
        acceptedLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        JLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel7.setForeground(new java.awt.Color(255, 255, 255));
        JLabel7.setText("CVV");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Card Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Card holder Name");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Secure Credit Card Payment ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Expiry Date (MM/YY)");

        FinishPaymentBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FinishPaymentBut.setForeground(new java.awt.Color(0, 102, 0));
        FinishPaymentBut.setText("Finish payment");
        FinishPaymentBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishPaymentButActionPerformed(evt);
            }
        });

        sendReceiptRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sendReceiptRB.setForeground(new java.awt.Color(255, 255, 255));
        sendReceiptRB.setText("Send billing receipt to email");
        sendReceiptRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReceiptRBActionPerformed(evt);
            }
        });

        cardNumberTF.setForeground(new java.awt.Color(0, 0, 0));
        cardNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberTFActionPerformed(evt);
            }
        });

        cardHolderNameTF.setForeground(new java.awt.Color(0, 0, 0));
        cardHolderNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardHolderNameTFActionPerformed(evt);
            }
        });

        CVVTF.setForeground(new java.awt.Color(0, 0, 0));
        CVVTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVTFActionPerformed(evt);
            }
        });

        cardHolderNameLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cardHolderNameLab.setForeground(new java.awt.Color(255, 0, 0));
        cardHolderNameLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        emailLab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLab.setForeground(new java.awt.Color(255, 255, 255));
        emailLab.setText("Email: ");

        emailTF.setForeground(new java.awt.Color(0, 0, 0));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        cardNumberLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cardNumberLab.setForeground(new java.awt.Color(255, 0, 0));
        cardNumberLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount in Rands:");

        amountTF.setForeground(new java.awt.Color(0, 0, 0));
        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });

        CVVLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CVVLab.setForeground(new java.awt.Color(255, 0, 0));
        CVVLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        amountLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amountLab.setForeground(new java.awt.Color(255, 0, 0));
        amountLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        yearLab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yearLab.setForeground(new java.awt.Color(255, 255, 255));
        yearLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLab.setText("0");

        yearSlider.setMinimum(2024);
        yearSlider.setPaintLabels(true);
        yearSlider.setPaintTicks(true);
        yearSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearSliderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yearSliderMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yearSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                yearSliderMouseReleased(evt);
            }
        });

        monthSlider.setMaximum(12);
        monthSlider.setMinimum(1);
        monthSlider.setPaintLabels(true);
        monthSlider.setPaintTicks(true);
        monthSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthSliderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monthSliderMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monthSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                monthSliderMouseReleased(evt);
            }
        });

        monthLab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        monthLab.setForeground(new java.awt.Color(255, 255, 255));
        monthLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthLab.setText("0");

        emailErrorLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailErrorLab.setForeground(new java.awt.Color(255, 0, 0));
        emailErrorLab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        acceptedLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acceptedLab.setForeground(new java.awt.Color(102, 204, 255));
        acceptedLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardHolderNameTF)
                            .addComponent(amountTF)
                            .addComponent(cardNumberTF)))
                    .addComponent(cardNumberLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amountLab, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardHolderNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CVVLab, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(yearLab, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CVVTF, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(monthLab, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(monthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailErrorLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sendReceiptRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                .addComponent(FinishPaymentBut))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emailLab)
                                .addGap(18, 18, 18)
                                .addComponent(emailTF)
                                .addGap(26, 26, 26)
                                .addComponent(acceptedLab, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(198, 198, 198))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cardHolderNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cardHolderNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardNumberLab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(monthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(monthLab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel7)
                            .addComponent(CVVTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(CVVLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(amountTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amountLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FinishPaymentBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acceptedLab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendReceiptRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLab)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yearLab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emailErrorLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinishPaymentButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishPaymentButActionPerformed
        // TODO add your handling code here:

        String cvvLengthOutput = BACKEND.CreditCardPayingScreenBACKEND.checkCVV(CVVTF.getText());
        boolean CVVAccepted = false;

        if (!cvvLengthOutput.equals("valid")) {
            CVVLab.setText(cvvLengthOutput);
        } else {
            CVVLab.setText("");
            CVVAccepted = true;
        }

        //card number checks
        boolean cardNumberAccepted = false;
        String cardNum = cardNumberTF.getText();
        String cardNumOutput = BACKEND.CreditCardPayingScreenBACKEND.checkCardNum(cardNum);
        if (!cardNumOutput.equals("valid")) {
            cardNumberLab.setText(cardNumOutput);
        } else {
            cardNumberLab.setText("");
            cardNumberAccepted = true;
        }

        //checks for card holder name
        boolean cardHolderNameAccepted = false;
        String onlyLettersInNameOutput = BACKEND.CreditCardPayingScreenBACKEND.checkCardHolderName(cardHolderNameTF.getText());
        if (!onlyLettersInNameOutput.equals("valid")) {

            cardHolderNameLab.setText(onlyLettersInNameOutput);
        } else {
            cardHolderNameLab.setText("");
            cardHolderNameAccepted = true;
        }

        //handle date
        //handle amount
        boolean amountAccepted = false;
        if (amountTF.getText().length() == 0) {
            amountLab.setText("The amount cannot be zero.");
        } else if (BACKEND.CreditCardPayingScreenBACKEND.hasOnlyNumbers(amountTF.getText())) {
            amountLab.setText("");
            amountAccepted = true;

            // !!!!! convert it to a double just to store it as the correct data type !!!!!
            BACKEND.CreditCardPayingScreenBACKEND.convertToDouble(amountTF.getText());

        } else {
            amountLab.setText("Only digits with one decimal place may be allowed.");
        }

        //handle email
        boolean emailAccepted = false;
        if (sendReceiptRB.isSelected()) {
            //get the email + do checks etc
            String email = emailTF.getText();
            String validEmailOutput = BACKEND.CreditCardPayingScreenBACKEND.isValidEmail(email);
            if (!validEmailOutput.equals("valid")) {
                emailErrorLab.setText(validEmailOutput);
            } else {
                emailErrorLab.setText("");
                emailAccepted = true;

            }
        }

        LocalDate date = BACKEND.CreditCardPayingScreenBACKEND.convertToDate("1/" + monthSlider.getValue() + "/" + yearSlider.getValue());
        if (CVVAccepted && cardNumberAccepted && cardHolderNameAccepted && amountAccepted && emailAccepted) {
            acceptedLab.setText("Payment completed and email sent!");
            BACKEND.CreditCardPayingScreenBACKEND.printPayment(cardHolderNameTF.getText(), cardNumberTF.getText(), date, CVVTF.getText(), BACKEND.CreditCardPayingScreenBACKEND.convertToDouble(amountTF.getText()), emailTF.getText());
        } else if (CVVAccepted && cardNumberAccepted && cardHolderNameAccepted && amountAccepted) {
            acceptedLab.setText("Payment completed!");
            BACKEND.CreditCardPayingScreenBACKEND.printPayment(cardHolderNameTF.getText(), cardNumberTF.getText(), date, CVVTF.getText(), BACKEND.CreditCardPayingScreenBACKEND.convertToDouble(amountTF.getText()));
        } else {
            acceptedLab.setText("");
        }

    }//GEN-LAST:event_FinishPaymentButActionPerformed

    private void sendReceiptRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReceiptRBActionPerformed
        // TODO add your handling code here:
        //handle email
        if (sendReceiptRB.isSelected()) {
            emailLab.setVisible(true);
            emailTF.setVisible(true);
        } else {
            emailLab.setVisible(false);
            emailTF.setVisible(false);
            emailErrorLab.setVisible(false);
        }
    }//GEN-LAST:event_sendReceiptRBActionPerformed

    private void cardHolderNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardHolderNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardHolderNameTFActionPerformed

    private void cardNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberTFActionPerformed

    private void CVVTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTFActionPerformed

    private void yearSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_yearSliderMouseClicked

    private void monthSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_monthSliderMouseClicked

    private void monthSliderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthSliderMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_monthSliderMouseEntered

    private void yearSliderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearSliderMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_yearSliderMouseEntered

    private void monthSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthSliderMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_monthSliderMousePressed

    private void yearSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearSliderMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_yearSliderMousePressed

    private void yearSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearSliderMouseReleased
        // TODO add your handling code here:
        yearLab.setText(yearSlider.getValue() + "");
    }//GEN-LAST:event_yearSliderMouseReleased

    private void monthSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthSliderMouseReleased
        // TODO add your handling code here:
        monthLab.setText(monthSlider.getValue() + "");
    }//GEN-LAST:event_monthSliderMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCardPayingScreenUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVVLab;
    private javax.swing.JTextField CVVTF;
    private javax.swing.JButton FinishPaymentBut;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JLabel acceptedLab;
    private javax.swing.JLabel amountLab;
    private javax.swing.JTextField amountTF;
    private javax.swing.JLabel cardHolderNameLab;
    private javax.swing.JTextField cardHolderNameTF;
    private javax.swing.JLabel cardNumberLab;
    private javax.swing.JTextField cardNumberTF;
    private javax.swing.JLabel emailErrorLab;
    private javax.swing.JLabel emailLab;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monthLab;
    private javax.swing.JSlider monthSlider;
    private javax.swing.JRadioButton sendReceiptRB;
    private javax.swing.JLabel yearLab;
    private javax.swing.JSlider yearSlider;
    // End of variables declaration//GEN-END:variables
}
